services:
  aideep-app-spring:
    build:
      context: .
    image: aideep-app-spring:latest
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      PORT: ${PORT:-8080}
      DD_TRACE_ENABLED: ${DD_TRACE_ENABLED:-true}
      DD_RUNTIME_METRICS_ENABLED: ${DD_RUNTIME_METRICS_ENABLED:-true}
      DD_METRICS_ENABLED: ${DD_METRICS_ENABLED:-true}
      DD_SERVICE: ${DD_SERVICE:-aideep}
      DD_ENV: ${DD_ENV:-prod}
      DD_VERSION: ${DD_VERSION:-0.0.1-SNAPSHOT}
      DD_TRACE_AGENT_URL: unix:///var/run/datadog/apm.socket
      DD_DOGSTATSD_SOCKET: /var/run/datadog/dsd.socket
    volumes:
      - /var/run/datadog:/var/run/datadog:ro
    network_mode: host
