my:
  nickname: PROD

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      ssl:
        enabled: ${REDIS_SSL:false}
server:
  port: ${PORT:8090}

management:
  statsd:
    metrics:
      export:
        protocol: uds_datagram
        # uds_datagram 에서는 host 가 소켓 경로로 사용된다
        host: ${DD_DOGSTATSD_SOCKET:/var/run/datadog/dsd.socket}

logging:
  level:
    com.aideep.domain: INFO
    com.aideep.global.exception.GlobalExceptionHandler: DEBUG
    com.aideep.global.config.SecurityConfig: DEBUG
